[supervisord]
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=true
; 设置事件监听确保顺序
events=PROCESS_STATE

[program:init_settings]
command=python -c "from bisheng.api import settings as ragflowSettings; ragflowSettings.init_settings()"
autorestart=false ; 只需运行一次
startsecs=0
priority=100 ; 最高优先级最先执行
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:update_progress]
command=python -c "from bisheng.api.services.document_service import DocumentService; import time, logging; while True: time.sleep(3); try: DocumentService.update_progress(); except: logging.exception('update_progress exception')"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
[program:run_workers]
command=/bin/bash /home/ewing/newProject/bisheng/docker/launch_backend_service.sh
autorestart=false ; 假设脚本是阻塞式启动服务
startsecs=0
priority=90 ; 在 init_settings 后执行
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:uvicorn]
command=uvicorn bisheng.main:app --host 0.0.0.0 --port 7860 --no-access-log --workers 2
autostart=false ; 等待手动触发
autorestart=true
priority=80
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A bisheng.worker.main worker -l info -c 4
autostart=false
autorestart=true
priority=70
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[eventlistener:trigger_main]
command=sh -c "echo '等待初始化完成...' && supervisorctl -c /etc/supervisor/supervisord.conf start uvicorn celery"
events=PROCESS_STATE_EXITED
process_name=run_workers
autorestart=false